dependencies = [
    "minsearch>=0.0.5",
    "openai>=1.108.2",
    "pydantic-ai==1.0.9",
    "python-frontmatter>=1.1.0",
    "requests>=2.32.5",
    "python-dotenv>=1.0.1",
    "groq>=0.9.0"
]

[dependency-groups]
dev = [
    "groq>=0.32.0",
    "minsearch>=0.0.7",
    "pydantic>=2.12.3",
    "pydantic-ai>=1.1.0",
    "python-frontmatter>=1.1.0",
    "requests>=2.32.5",
    "streamlit>=1.50.0",
    "tqdm>=4.67.1",
]
