name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      # Disponibiliza para os testes que precisarem
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      PYTHONWARNINGS: default
    steps:

      - name: Lint
        run: ruff check .

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install project deps (if present)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -r requirements-dev.txt

      - name: Run tests with coverage
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=. --cov-report=term-missing --cov-report=xml

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
